/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StakeCaRouteImport } from './routes/stake.$ca'
import { Route as ApiPublicArtCaRouteImport } from './routes/api/public/art/$ca'
import { Route as ApiPublicOgCaRouteImport } from './routes/api/public/og/$ca'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeCaRoute = StakeCaRouteImport.update({
  id: '/stake/$ca',
  path: '/stake/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtCaRoute = ApiPublicArtCaRouteImport.update({
  id: '/api/public/art/$ca',
  path: '/api/public/art/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgCaRoute = ApiPublicOgCaRouteImport.update({
  id: '/api/public/og/$ca',
  path: '/api/public/og/$ca',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stake/$ca': typeof StakeCaRoute
  '/api/public/art/$ca': typeof ApiPublicArtCaRoute
  '/api/public/og/$ca': typeof ApiPublicOgCaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stake/$ca': typeof StakeCaRoute
  '/api/public/art/$ca': typeof ApiPublicArtCaRoute
  '/api/public/og/$ca': typeof ApiPublicOgCaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stake/$ca': typeof StakeCaRoute
  '/api/public/art/$ca': typeof ApiPublicArtCaRoute
  '/api/public/og/$ca': typeof ApiPublicOgCaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stake/$ca' | '/api/public/art/$ca' | '/api/public/og/$ca'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stake/$ca' | '/api/public/art/$ca' | '/api/public/og/$ca'
  id:
    | '__root__'
    | '/'
    | '/stake/$ca'
    | '/api/public/art/$ca'
    | '/api/public/og/$ca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StakeCaRoute: typeof StakeCaRoute
  ApiPublicArtCaRoute: typeof ApiPublicArtCaRoute
  ApiPublicOgCaRoute: typeof ApiPublicOgCaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake/$ca': {
      id: '/stake/$ca'
      path: '/stake/$ca'
      fullPath: '/stake/$ca'
      preLoaderRoute: typeof StakeCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/art/$ca': {
      id: '/api/public/art/$ca'
      path: '/api/public/art/$ca'
      fullPath: '/api/public/art/$ca'
      preLoaderRoute: typeof ApiPublicArtCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$ca': {
      id: '/api/public/og/$ca'
      path: '/api/public/og/$ca'
      fullPath: '/api/public/og/$ca'
      preLoaderRoute: typeof ApiPublicOgCaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StakeCaRoute: StakeCaRoute,
  ApiPublicArtCaRoute: ApiPublicArtCaRoute,
  ApiPublicOgCaRoute: ApiPublicOgCaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
